App\Entity\Category:
    type: entity
    table: category
    repositoryClass: App\Repository\CategoryRepository
    id:
        id:
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        name:
            type: string
            scale: null
            length: 255
            unique: false
            nullable: false
            precision: null
    manyToMany:
        books:
            targetEntity: App\Entity\Book
            cascade: {  }
            fetch: LAZY
            mappedBy: categories
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
